server:
  port: 8080

spring:
  application:
    name: ai-chat-backend

  datasource:
    url: jdbc:h2:file:./data/chatdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  ai:
    openai:
      api-key: "dummy"
      chat:
        options:
          model: "gpt-4.1-nano"       #working with Spring AI 1.0.2
          #model: "gpt-5-nano"
          temperature: 1.0
          max-tokens: 1000
    ollama:
      base-url: "http://localhost:11434"
      chat:
        options:
          model: "llama3.2:3b"
          temperature: 0.7
          max-tokens: 1000
      enabled: true

logging:
  level:
    org.springframework.ai: INFO
    org.springframework.boot.autoconfigure: INFO    